const locations = [
  {
    id: 1,
    name: "Valente Lifespace Creations Private Limited",
    project: "Pavagada Solar Project",
    area: "Pavagada, Karnataka",
    lat: 14.1000,
    lng: 77.2800,
    image: "/images/pavagada.jpg",
    description: "Renewable energy project completed at Pavagada, Karnataka",
  },
  {
    id: 2,
    name: "Swelect Energy Systems Limited",
    project: "Mondipatti Solar Project",
    area: "Mondipatti, Trichy, Tamil Nadu",
    lat: 10.7905,
    lng: 78.7047,
    image: "/images/trichy.jpg",
    description: "Solar power project completed near Trichy region",
  },
  {
    id: 3,
    name: "Adani Green Energy",
    project: "Kadapa Solar Project",
    area: "Kadapa, Andhra Pradesh",
    lat: 14.4674,
    lng: 78.8241,
    image: "/images/kadapa.jpg",
    description: "Large-scale renewable energy project in Kadapa district",
  },
  {
    id: 4,
    name: "Ayana Kadapa Renewables",
    project: "Gulbarga Renewable Project",
    area: "Gulbarga (Kalaburagi), Karnataka",
    lat: 17.3297,
    lng: 76.8343,
    image: "/images/gulbarga.jpg",
    description: "Wind and solar renewable energy project in Gulbarga",
  },
  {
    id: 5,
    name: "Avaada Clean Energy",
    project: "Gadag Solar Project",
    area: "Gadag, Karnataka",
    lat: 15.4298,
    lng: 75.6356,
    image: "/images/gadag.jpg",
    description: "Clean energy project completed in Gadag district",
  },
];

export default locations;
